-- Vector Love: age filters, permanent skips, VIP expiry

alter table public.users
  add column if not exists age_min integer default 18,
  add column if not exists age_max integer default 80,
  add column if not exists vip_until timestamptz;

update public.users
set age_min = 18
where age_min is null;

update public.users
set age_max = 80
where age_max is null;

create table if not exists public.skips (
  id bigint generated by default as identity primary key,
  from_user bigint not null,
  to_user bigint not null,
  created_at timestamptz not null default now(),
  constraint skips_from_to_unique unique (from_user, to_user)
);

create index if not exists skips_from_user_idx
  on public.skips (from_user);

create index if not exists skips_to_user_idx
  on public.skips (to_user);
