create table if not exists public.skips (
  id bigint generated by default as identity primary key,
  from_user bigint not null,
  to_user bigint not null,
  created_at timestamptz not null default now(),
  unique (from_user, to_user)
);

create index if not exists skips_from_user_idx on public.skips (from_user);
create index if not exists skips_to_user_idx on public.skips (to_user);
